[package]
name = "rakuen-enity"
version = "0.1.0"
edition.workspace = true
readme.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
sea-orm = { workspace = true }
